NyaAccent для ушек
Workbench-Team/space-station-14 pull request #1
Opened 2022-11-17 11:59 UTC by CaptainSqrBeard

## About the PR 

**Screenshots**

**Changelog**
Отдельный акцент для ушек, дабы их не путали с чем-то фурряшным. ~~На оффы продвинуть не получилось~~
Потом сделаю перевод для master-ru

Сам акцент иногда добавляет кошачьи звуки в конце предложений и заменяет некоторые слова на другие.

:cl: csqrb
- add: added Nya Accent
- tweak: Cat Ears now using Nya Accent instead of OwO Accent

2022-11-17 12:17 UTC, illersaver commented
🐈

2022-11-17 12:28 UTC, AruMoon requested changes
Ты где-то что-то забыл, потому что оно не собирается

2022-11-17 13:22 UTC, CaptainSqrBeard commented
Так, теперь должно билдится

2022-11-17 13:53 UTC, CaptainSqrBeard commented
Ветка arumoon-server с локализацией на русский же. А акцент у меня не локализован ещё.

2022-11-18 05:25 UTC, AruMoon approved these changes

2022-11-18 05:26 UTC, AruMoon commented
Будет замечательно если сделаешь локализацию

2022-11-19 18:16 UTC, CaptainSqrBeard commented
с локализацией идеи нужны для слов которые можно заменять, вроде "замечательно" которое заменяется на "замурчательно".

2022-11-22 14:04 UTC, merged