.35 magazine in uplink
Workbench-Team/space-station-14 pull request #116
Opened 2023-04-07 12:34 UTC by DjfjdfofdjfjD

## О запросе слияния

Небольшой фикс присутствующего ныне перевода, а так же добавление магазина для пистолета-пулемёта в аплинк. Сейчас в аплинке присутствует магазин для гадюки, которая стреляет такими же патронами. В нём находится 10 патронов калибра .35, а сам магазин стоит 1 ТК. Умные нюкеры покупают его для пополнения запасов, просто пересыпая патроны в магазин для С-20r. Сейчас в аплинке нет магазина для самого популярного оружия у нюкеров, что я считаю неудобным и несправедливым. Магазин для C-20r стоит 3 ТК, в нём находится 30 патронов. 

**Медиа**

- [X] Я добавил скриншоты/видео к этому запросу слияния, демонстрирующие его изменения в игре, **или** этот запрос слияния не требует демонстрации в игре

**Чейнджлог**

:cl:
- add: В аплинк добавлен магазин для C-20r
- fix: Небольшие фиксы перевода

2023-04-09 12:40 UTC, Mr0maks requested changes

2023-04-09 12:40 UTC, Mr0maks commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-pistol-magazine-desc = Пистолетный магазин с 10 патронами. Подходит для Гадюки.
Фиксы перевода только в master-ru

2023-04-09 12:40 UTC, Mr0maks commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-emp-grenade-desc = Выпускает электромагнитные импульсы, которые выводят из строя или повреждают многие электронные устройства, а так же разряжают элементы питания.
Так же фиксы только в master-ru

2023-04-09 12:49 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-emp-grenade-desc = Выпускает электромагнитные импульсы, которые выводят из строя или повреждают многие электронные устройства, а так же разряжают элементы питания.
Ты хочешь чтобы я откатил изменения перевода?

2023-04-10 17:11 UTC, Mr0maks approved these changes

2023-04-10 17:11 UTC, merged