Syringe Gun
Workbench-Team/space-station-14 pull request #154
Opened 2023-05-02 06:44 UTC by Wizard-Grin

## О запросе слияния
Добавил шприцемет, однозарядная версия в шкафчик для врачей и 8 зарядная медику яо. Картриджи шприцемета можно заряжать через химку либо наполнять с помощью сосудов. Добавил в аплинк возможность покупки дополнительных картриджей, а так же крафт в медфаб.

**Медиа**
![base](https://user-images.githubusercontent.com/100096262/235597311-1ece8a33-470f-468b-973b-e8ee8201bcbe.png)

- [x] Я добавил скриншоты/видео к этому запросу слияния, демонстрирующие его изменения в игре, **или** этот запрос слияния не требует демонстрации в игре

**Чейнджлог**

:cl:
- add: Добавлен шприцемет в шкафчики медиков, шприцеметный пистолет для медика яо. Добавлена возможность создавать картриджи в медфабе, а так же возможность закупить картриджи в аплинке(только для яо).

2023-05-02 07:18 UTC, DjfjdfofdjfjD commented on Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/weapons/guns/smgs/smgs.ftl
> +    .desc = A single-shot syringe gun provided by HT specifically for medics. Uses syringe cartridges
> "A single-shot syringe gun provided by HT specifically for medics"
Что за ХТ? Это английская локализация, там NT должно быть

2023-05-02 07:24 UTC, DjfjdfofdjfjD commented
Не думал добавить в аплинк картриджи на 10 юнитов? Улучшенные синдикатом, все дела

2023-05-03 00:36 UTC, Mr0maks requested changes
Небольшие странности. Так всё в порядке.

2023-05-03 00:36 UTC, Mr0maks commented on Resources/Prototypes/Catalog/Fills/Boxes/ammunition.yml
> +  description: A box full of pistol .35 auto magazines.
Неправильное описание из за copy-paste

2023-05-03 00:36 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/dartgun.yml
> +  components:
нету описания

2023-05-03 00:36 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/dartgun.yml
> +  parent: BaseItem
нету описания

2023-05-03 00:36 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/dartgun.yml
> +  noSpawn: true
нету описания

2023-05-03 00:36 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A syringe pistol developed by the Syndicate organization. Uses syringe cartridges.
Странная структура. Может лучше чтобы name и description были рядом?

2023-05-03 04:45 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A syringe pistol developed by the Syndicate organization. Uses syringe cartridges.
Я делал все по образу и подобию остальных имеющихся оружий. В каждом прототипе оружия была такая структура написания, чтобы ее не нарушать, я сделал так-же, чтобы для будущего чтения было легче для восприятия. Если и в правду надо изменить структуру, могу поменять сразу во всем файле для каждого прототипа.

2023-05-03 04:46 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/dartgun.yml
> +  noSpawn: true
Описания нету ни у одного проджектайла во всех файлах проджектайлов 
![image](https://user-images.githubusercontent.com/100096262/235834379-9cc10ccf-181a-4197-bbd5-5c88f982076b.png)
![image](https://user-images.githubusercontent.com/100096262/235834394-cdee4fd5-49d9-45dc-8d44-c5086c3ced7e.png)

2023-05-03 04:46 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/dartgun.yml
> +  parent: BaseItem
Такая же ситуация, как и с проджектайлом. Дабы не нарушать общую структуру прототипов, описания нету, ибо нету описания и у остальных магазинов.

2023-05-03 04:47 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/dartgun.yml
> +  components:
Такая же ситуация, как и с проджектайлом. Дабы не нарушать общую структуру прототипов, описания нету, ибо нету описания и у остальных патронов.

2023-05-03 04:50 UTC, Wizard-Grin commented on Resources/Prototypes/Catalog/Fills/Boxes/ammunition.yml
> +  description: A box full of pistol .35 auto magazines.
Недоглядел. Исправлено

2023-05-03 15:00 UTC, Mr0maks approved these changes

2023-05-03 15:01 UTC, merged