Translate upstream update
Workbench-Team/space-station-14 pull request #155
Opened 2023-05-02 18:28 UTC by MilenVolf

Выполнен апстримовский перевод.

2023-05-02 18:31 UTC, AruMoon commented
Проверю завтра

2023-05-02 19:55 UTC, MilenVolf commented
> Проверю завтра

Было только одно затруднение: с новым напитком Ратвара. Я полагал, что Cogchamp образован от - Cognac(Коньяка) и Champage(шампанского), но если честно уже не уверен.

2023-05-02 20:49 UTC, Mr0maks requested changes
Ты кое что забыл а так LGTM.

2023-05-02 20:49 UTC, Mr0maks commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/flesh.ftl
>  ent-MobAbomination = abomination
Забыл перевести

2023-05-02 22:00 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/flesh.ftl
>  ent-MobAbomination = abomination
А, пропустил видимо. Щас допилем

2023-05-03 00:29 UTC, Mr0maks approved these changes
LGTM

2023-05-03 00:30 UTC, merged

2023-05-03 02:26 UTC, DjfjdfofdjfjD commented
> > Проверю завтра
> 
> Было только одно затруднение: с новым напитком Ратвара. Я полагал, что Cogchamp образован от - Cognac(Коньяка) и Champage(шампанского), но если честно уже не уверен.

Это образовано от погчамп и ког