Added Arumoon part into guidebook with corp law and introduction.
Workbench-Team/space-station-14 pull request #163
Opened 2023-05-09 17:56 UTC by PilgrimViis

## О запросе слияния
Я добавил в игровой учебник раздел с особенностями сервера Ару. На данный момент внес туда только 1 раздел "Корп. закон". Обсуждение тут
https://discord.com/channels/727015266642296924/1037396123985379338/1105516978342461440

![image](https://github.com/Workbench-Team/space-station-14/assets/6408195/9c134acb-defd-46c0-8b29-bc494f1e1996)

P.S. Guidebook это часть ресурсов клиента.

2023-05-09 18:21 UTC, Ser11y commented
Объективно, это нам надо. Даже вкладку открывать не придётся... 👍

2023-05-10 16:40 UTC, Mr0maks requested changes
Пути для нормальных ос сломаны. Поправь пожалуйста.

2023-05-10 16:40 UTC, Mr0maks commented on Resources/Prototypes/Guidebook/arumoon.yml
> +  text: "/ServerInfo/Guidebook/Arumoon/AruMoon.xml"
```/ServerInfo/Guidebook/AruMoon/AruMoon.xml```
В нормальных ос (GNU\Linux, other posix compaible). Пути чувствительны к регистру.

2023-05-10 16:40 UTC, Mr0maks commented on Resources/Prototypes/Guidebook/arumoon.yml
> +  text: "/ServerInfo/Guidebook/Arumoon/CorpLaw.xml"
```/ServerInfo/Guidebook/AruMoon/CorpLaw.xml```
В нормальных ос (GNU\Linux, other posix compaible). Пути чувствительны к регистру.

2023-05-10 17:07 UTC, Mr0maks requested changes
Проглядел. Вот ещё правки. И само название файла так же надо поменять.

2023-05-10 17:07 UTC, Mr0maks commented on Resources/Locale/ru-RU/guidebook/guides.ftl
> +guide-entry-arumoon-corplaw = Корпоративный Закон
Космический закон.

2023-05-10 17:07 UTC, Mr0maks commented on Resources/ServerInfo/Guidebook/AruMoon/CorpLaw.xml
> +# Корпоративный закон
Космический закон

2023-05-10 18:48 UTC, Mr0maks approved these changes
LGTM после ci тестов

2023-05-10 20:57 UTC, merged