Bwoink button to save my ears
Workbench-Team/space-station-14 pull request #174
Opened 2023-05-29 08:42 UTC by Cooderer

Some shitcode for QoL

Я добавил целую кнопку которая сохраняет стейтмент и позволяет вырубить звук ахелпа при приходе сообщения в самом ахелпе
Стейтмент сетапится в структуре, потому по умолчанию всегда звук есть
Обходной путь, написан через LocalPlayer, потому что я не хочу трогать ивенты

2023-05-29 08:59 UTC, Cooderer commented
Я инвалид в движок накакал

2023-05-29 11:08 UTC, Cooderer commented
Try again
Но теперь через интерфейс

2023-05-31 05:04 UTC, AruMoon requested changes
Сделай локализацию

2023-05-31 05:14 UTC, AruMoon approved these changes

2023-05-31 05:14 UTC, merged