Arumoon server
Workbench-Team/space-station-14 pull request #175
Opened 2023-06-02 04:18 UTC by Elst28

## О запросе слияния

**Медиа**
Добавила двери с доступом для ЯОшников и Командира\Медика ЯОшников.
Был исправлен КПК представителя ЦК (Раньше на альт+ЛКМ доставалась сначала ручка а потом айди карта, а ещё был доступ только в теха), так-же было исправлено снаряжения (Раньше он был совсем бомжэ), теперь он появляется с более нормальным снаряжениям.
Так-же теперь айди карты кэпа\медика ЯОшников могут работать как карты агентов

- [X] Двери и айди карты синдиката
- [ ] Перемапить шатл и базу ЯОшников под новые двери
**Чейнджлог**

:cl:
- add: Добавлены двери с доступом синдиката
- add: Добавлена возможность использовать айди карту синдиката как агентскую
- tweak: Изменено стартовое снаряжения ПЦК

2023-06-02 04:46 UTC, Mr0maks requested changes
LGTM, надо небольшие правки сделать как по мне.

2023-06-02 04:46 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Devices/pda.yml
> -    penSlot:
Это нормально что у кпк центком пропал слот для ручки в прототипе?

2023-06-02 04:46 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
>    parent: IDCardStandard
Можно же взять parent от агентской карты?

2023-06-02 04:46 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +  parent: IDCardStandard
Можно же взять parent от агентской карты?

2023-06-02 04:46 UTC, Mr0maks commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +    gloves: ClothingHandsGlovesCombat
Странное изменения, точно у простого работничка центком должны быть боевые перчатки?

2023-06-02 04:46 UTC, Mr0maks commented on Resources/Textures/Objects/Misc/id_cards.rsi/meta.json
Файл имеет странное форматирование, переформатируй RSIEditor

2023-06-02 04:59 UTC, Elst28 commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +    gloves: ClothingHandsGlovesCombat
Я это сделала по той причине что это как-бы представитель ЦК и он отправлен на станцию по важному (Или не очень) заданию, странно как-то что у него не изолированные перчатки (По факту ПЦК где-то на уровне кэпа, а у кэпа есть свои изоли), да и вообще странно что такой важный человек может помереть от обычной наэлектризованной двери

2023-06-02 05:12 UTC, Elst28 commented on Resources/Prototypes/Entities/Objects/Devices/pda.yml
> -    penSlot:
Я это сделала чтобы пофиксить то что сначала доставался КПК а уже потом ручка, уже поправила и в КПК лежит ручка ЦК

2023-06-02 05:29 UTC, Elst28 commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
>    parent: IDCardStandard
При изменении parent на агентскую карту пропадает доступ к дверям синдиката

2023-06-02 07:50 UTC, AruMoon commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
> +ent-SyndicateIDCard = ID карта элиты синдиката
Зачем надо было это менять?

2023-06-02 11:18 UTC, Mr0maks requested changes

2023-06-02 11:18 UTC, Mr0maks commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
> +ent-SyndicateIDCard = ID карта элиты синдиката
Oops, зачем это изменение?

2023-06-02 12:04 UTC, Elst28 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
> +ent-SyndicateIDCard = ID карта элиты синдиката
Было сделано чтобы подчеркнуть то что эта карта принадлежит не обычному члену синдиката (У неё доступ к командным дверям синдиката), хотя и в самой игре это не видно и изменения можно заметить только в меню щитспана, так-же только они могут обьявлять войну

2023-06-03 03:53 UTC, Mr0maks approved these changes
LGTM

2023-06-03 23:48 UTC, AruMoon requested changes

2023-06-03 23:48 UTC, AruMoon commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +    belt: WeaponDisabler
Не нужно давать дизейблер представителю. Его должны охранять сопровождающие или СБ. Задерживать преступников это точно не задача представителя

2023-06-03 23:48 UTC, AruMoon commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +    gloves: ClothingHandsGlovesCombat
ЦК посылают представителя когда на станции ситуация считается только безопасной. Техническим обслуживанием станции он также не занимается. Так что ему эти перчатки не нужны

2023-06-03 23:48 UTC, AruMoon commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +    back: ClothingBackpackSatchelCaptainFilled
Он не является капитаном. В таком случае лучше либо сделать ему отдельный рюкзак без телескопа, либо не добавлять рюкзак вообще

2023-06-04 06:26 UTC, Elst28 commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +    back: ClothingBackpackSatchelCaptainFilled
Переделала, добавила центкоммовскую сумку

2023-06-04 06:27 UTC, Elst28 commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +    belt: WeaponDisabler
Ок, убрала

2023-06-05 00:20 UTC, AruMoon approved these changes

2023-06-05 00:27 UTC, AruMoon requested changes
Ты забыл между некоторыми прототипами пробелы расставить

2023-06-05 10:42 UTC, AruMoon approved these changes

2023-06-05 10:43 UTC, merged