Upstream Translation - Omega Edition
Workbench-Team/space-station-14 pull request #176
Opened 2023-06-02 11:04 UTC by MilenVolf

## О запросе слияния

Долгожданный перевод апстрима. Омега эдишен...

2023-06-02 11:07 UTC, MilenVolf commented
Не смотрите на страшные коммиты Кудера, он в браузере редачил xD

2023-06-02 16:26 UTC, MilenVolf commented on Resources/Locale/ru-RU/prototypes/catalog/fills/crates/engineering-crates.ftl
Не обращайте внимания на подобные штуки, это для удобства читаемости.

2023-06-03 23:06 UTC, AruMoon requested changes
Не было смысла добавлять пробелы в локализации прототипов. Эти файлы генерируются и обновляются скриптом поэтому при следующем обновлении все эти пробелы снова пропадут. Также не используйте чисто английские функции локали, типо того же THE и CONJUGATE-BE. Вместо POSS-ADJ нужно самому писать местоимение

2023-06-03 23:06 UTC, AruMoon commented on Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
> +petting-success-mimebot = Вы гладите { THE($target) } по его { POSS-ADJ($target) } холодной металлической голове.
POSS-ADJ и THE нет в русской локали
```suggestion
petting-success-mimebot = Вы гладите { $target } по его холодной металлической голове.
```

2023-06-03 23:06 UTC, AruMoon commented on Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
> +petting-failure-mimebot = Вы тянетесь погладить { THE($target) }, но { SUBJECT($target) } { CONJUGATE-BE($target) } занят мимовством!
Тоже самое, CONJUGATE-BE также нет в русском
```suggestion
petting-failure-mimebot = Вы тянетесь погладить { $target }, но { $target } занят мимовством!
```

2023-06-03 23:06 UTC, AruMoon commented on Resources/Locale/ru-RU/reagents/meta/consumable/drink/alcohol.ftl
> +reagent-name-cogchamp = когчамп
лучше вернуть как было

2023-06-03 23:06 UTC, AruMoon commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/back/specific.ftl
> +    .desc =  Вмещает большое количество жидкостей. Принадлежности для распылительных форсунок в ваших руках.
опечатка - лишний пробел
```suggestion
    .desc = Вмещает большое количество жидкостей. Принадлежности для распылительных форсунок в ваших руках.
```

2023-06-03 23:06 UTC, AruMoon commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
> +    .suffix = { "Злой" }
Здесь не нужны ковычки и скобки
```suggestion
    .suffix = Злой
```

2023-06-03 23:06 UTC, AruMoon commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks.ftl
> +ent-DrinkCogChampBase = бокал когчампа
тоже верни

2023-06-03 23:09 UTC, AruMoon commented
А ещё я не вижу чтобы была убрана удалённая оригинальная локаль

2023-06-03 23:14 UTC, AruMoon requested changes
+ не были применены изменения в уже существующей локали из этих обновлений https://git.arumoon.ru/Workbench-Team/space-station-14/-/commit/57e679947caa6a1091396b26150a230a9c11661f?expanded=1&page=23
https://git.arumoon.ru/Workbench-Team/space-station-14/-/commit/1bbb5d19f74026758600a2c879f8213b6c06450e

Вы перевели только новые строки

2023-06-04 04:02 UTC, MilenVolf commented on Resources/Locale/ru-RU/reagents/meta/consumable/drink/alcohol.ftl
> +reagent-name-cogchamp = когчамп
Я просто помню, что говорили надо было просто оставить когчамп и вроде ты даже это правил, но видимо передумал

2023-06-04 04:04 UTC, AruMoon commented on Resources/Locale/ru-RU/reagents/meta/consumable/drink/alcohol.ftl
> +reagent-name-cogchamp = когчамп
Я потом решил такой вариант

2023-06-05 00:17 UTC, AruMoon requested changes

2023-06-05 00:17 UTC, AruMoon commented on Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
> +petting-success-mimebot = Вы гладите { $target } по его { $target } холодной металлической голове.
Убери вообще этот { target } второй
```suggestion
petting-success-mimebot = Вы гладите { $target } по его холодной металлической голове.
```

2023-06-05 00:18 UTC, AruMoon approved these changes

2023-06-05 00:18 UTC, merged