Cloth&radio hl2
Workbench-Team/space-station-14 pull request #185
Opened 2023-06-21 11:35 UTC by Elst28

## О запросе слияния

 Добавлены униформы HECU и гражданских из халф лайфа, также добавлено радио которое сравнится в техах и издаёт жуткие звуки (тоже из халф лайфа). Униформу хеку можно взять в охраншкафе, форму гражданского в одеждамате 

**Медиа**

- [ ] Я добавил скриншоты/видео к этому запросу слияния, демонстрирующие его изменения в игре, **или** этот запрос слияния не требует демонстрации в игре

**Чейнджлог**

:cl:
- add: Добавленны униформы HECU и гражданских из халф лайфа

2023-06-21 12:02 UTC, Elst28 commented
Так, вижу какая-то хуйня, сейчас буду разбираться

2023-06-21 14:18 UTC, MilenVolf commented on Resources/Locale/en-US/ss14-ru/prototypes/workbenchteam/entities/objects/fun/UnityRadio.ftl
> +    .suffix = { "" }
В конце всегда должна быть пустая строка

2023-06-21 14:18 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .suffix = { "" }
И тут

2023-06-21 14:18 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/workbenchteam/entities/objects/fun/UnityRadio.ftl
> +    .suffix = { "" }
И тут

2023-06-21 14:18 UTC, MilenVolf commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/civilian.rsi/meta.json
> +}
И тут

2023-06-21 14:18 UTC, MilenVolf commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/hecu.rsi/meta.json
> +}
И тут

2023-06-21 14:18 UTC, MilenVolf commented on Resources/Textures/Objects/Fun/hl_radio.rsi/meta.json
> +}
И тут

2023-06-26 13:56 UTC, AruMoon requested changes
Укажи лицензию на unity fm. Что это и откуда

2023-06-28 09:39 UTC, Elst28 commented
Насколько я поняла, это саунд из халф лайфа 2 (Radio),  его вообще можно пихнуть? И какую лицензию нужно указывать?

2023-06-28 10:04 UTC, Elst28 commented
Так, сейчас приведу всё в нормальный вид, ибо что-то возникла проблемка в гитхабом.

2023-07-04 17:29 UTC, closed without merging