TG-zation: Nukieplanet & Infiltrator
Workbench-Team/space-station-14 pull request #189
Opened 2023-06-30 17:58 UTC by MilenVolf

## ТГ-зация планеты и шаттла ЯО

**Медиа**

- [x] Я добавил скриншоты `nukieplanet.yml` и `infiltrator.yml`.
- [x] Я убедился в работе ивента `Nukeops` с новой станцией и шаттлом.

![NukeopsPlanet-0](https://github.com/Workbench-Team/space-station-14/assets/63782763/f389aab1-78cb-451c-ac39-a5eba451ceb3)
![NukeopsInfil-0](https://github.com/Workbench-Team/space-station-14/assets/63782763/efae0fc2-98e4-48d2-b8ad-3f48b98dbc9d)

**Чейнджлог**

:cl:
- tweak: Планета Ядерных Оперативников и их Шаттл были заменены на новые версии по прототипу TG.

2023-06-30 18:02 UTC, MilenVolf commented
@AruMoon Добавь пожалуйста в участники @Ratyyy

2023-07-01 03:51 UTC, AruMoon requested changes

2023-07-01 03:51 UTC, AruMoon commented on Resources/Locale/ru-RU/station-events/events/cargo-gifts.ftl
> +cargo-gifts-event-announcement = Поздравляем! { $sender } решил отправить на станцию { $description } в { $dest }. Вы сможете это найти в следующей партии груза на карго шаттле.
В master-ru эдиты локали надо

2023-07-01 06:49 UTC, MilenVolf commented on Resources/Locale/ru-RU/station-events/events/cargo-gifts.ftl
> +cargo-gifts-event-announcement = Поздравляем! { $sender } решил отправить на станцию { $description } в { $dest }. Вы сможете это найти в следующей партии груза на карго шаттле.
Хорошо

2023-07-01 15:57 UTC, AruMoon approved these changes

2023-07-01 15:57 UTC, merged