Ghetto surg... Chemistry V3
Workbench-Team/space-station-14 pull request #209
Opened 2023-07-31 15:56 UTC by DjfjdfofdjfjD

## О запросе слияния

**Допиленная** версия #207, вроде как рабочая. Новым ПРом потому что я с бранчами напортачил люто
Добавляет возможность измельчать некоторые вещи, чего достаточно для варки этих наркотиков **без доступа в химию:**

1. Метафетамин
2. Импедризин
3. Космические Наркотики
И другие препараты...

**Медиа**

- [X] Я добавил скриншоты/видео к этому запросу слияния, демонстрирующие его изменения в игре, **или** этот запрос слияния не требует демонстрации в игре

**Чейнджлог**

:cl:
- tweak: В измельчителе теперь можно выжимать или измельчать новые предметы, чего достаточно для создания некоторых наркотиков и препаратов в "домашних" условиях.

2023-07-31 17:15 UTC, MilenVolf requested changes

2023-07-31 17:15 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +        - ReagentId: Sugar
5 Сахара заменяет 10 унаследованных Нутриентов. Да и не только сахар в батончике. Сахар сейчас не утоляет голод, так что добавляй ещё 10 нутриентов. К тому же ты убрал максимальный объём, что у парента в 30. Так что чини.

2023-07-31 17:15 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +       - ReagentId: Iodine
Почему ручки буду состоять из Йода?

2023-07-31 17:15 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +        - ReagentId: Sugar
Тут тоже самое

2023-07-31 17:15 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> -        maxVol: 1
Верни ограничение ёмкости.

2023-07-31 17:15 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Power/lights.yml
> +       - ReagentId: Nitrogen
В лампочках нет Азота, это миф. В прошлом был, но от этого быстро отказались, в связи с быстрой изнашиваемостью. Так что там Вакуум.

2023-07-31 17:21 UTC, DjfjdfofdjfjD commented on Resources/Prototypes/Entities/Objects/Power/lights.yml
> +       - ReagentId: Nitrogen
> В лампочках нет Азота, это миф. В прошлом был, но от этого быстро отказались, в связи с быстрой изнашиваемостью. Так что там Вакуум.

Это взято с ТГ и нужно для расширения возможностей гетто химии, без этого Мет не сделать

2023-07-31 17:21 UTC, DjfjdfofdjfjD commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +       - ReagentId: Iodine
> Почему ручки буду состоять из Йода?

Условно чернила, взято с ТГ, тоже для мета

2023-07-31 17:22 UTC, DjfjdfofdjfjD commented on Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
> +        - ReagentId: Sugar
> 5 Сахара заменяет 10 унаследованных Нутриентов. Да и не только сахар в батончике. Сахар сейчас не утоляет голод, так что добавляй ещё 10 нутриентов. К тому же ты убрал максимальный объём, что у парента в 30. Так что чини.

поправлю это

2023-07-31 17:23 UTC, MilenVolf requested changes

2023-07-31 17:23 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Tools/glowstick.yml
> +  - type: Extractable
У тебя съехал Тип влево, из-за этого ошибки.

2023-08-01 07:03 UTC, DjfjdfofdjfjD commented
merge my pr
now

2023-08-01 07:38 UTC, MilenVolf approved these changes

2023-08-01 07:41 UTC, MilenVolf commented
Наверное стоит переименовать на "Extractable items" или что-то в этом роде. "Chemistry V3" звучит так, будто была перелопачена сама Химия.

2023-08-01 08:06 UTC, DjfjdfofdjfjD commented
> Наверное стоит переименовать на "Extractable items" или что-то в этом роде. "Chemistry V3" звучит так, будто была перелопачена сама Химия. Название ПР-а должно говорить, что он изменил.

не думаю, этот пр называется в честь гайда на вики ТГ "Guide to Ghetto Chemistry", благодаря которому эта идея и появилась

2023-08-01 09:11 UTC, MilenVolf commented
> > Наверное стоит переименовать на "Extractable items" или что-то в этом роде. "Chemistry V3" звучит так, будто была перелопачена сама Химия. Название ПР-а должно говорить, что он изменил.
> 
> не думаю, этот пр называется в честь гайда на вики ТГ "Guide to Ghetto Chemistry", благодаря которому эта идея и появилась

Лично мне не нравится, что у нас люди делают названия пр-ов по приколу. Говорящие названия нужны для того, чтобы если понадобится, легко найти и воспользоваться этим в будущем или наоборот откатить в случае чего. Да это конечно маленький пр на прототипе, но в любом случае я бы рекомендовал сделать название соответствующее изменениям, а не только лишь вдохновению. Как допустим рандомный человек, зайдя на этот пр, поймёт по названию о чём он и что меняет?

2023-08-01 09:12 UTC, MilenVolf commented
Допустим: "Extractable items for Ghetto Chemistry". Так пойдёт

2023-08-01 10:16 UTC, MilenVolf commented
В ченджлоге поменяй слово "новые" на "некоторые"

2023-08-01 10:54 UTC, Mr0maks approved these changes
Теперь СБ будет чем заняться. LGTM.

2023-08-01 10:55 UTC, merged