Слот и небольшая система для носков. Включая 31 новый вид их расцветки.
Workbench-Team/space-station-14 pull request #241
Opened 2023-09-11 11:43 UTC by ITamiokiI

## О запросе слияния
Добавляет отдельный слот для носков, и 31 разновидность расцветок носков, включая по 2-3 вида их длинны для каждой расцветки(В общей сумме 85 новых носков). Все носки добавлены в Шкафы отделов, Локеты глав, а так же в экипировку всех должностей. Вид носков может изменяться от выбора одежды (Юбка-Комбинезон/Комбинезон).

## Почему / Баланс
В игре имелись носки, но их слой отображения был сломан, отображаясь по верх юбки-комбинезона. Я решил исправить данную проблему, добавив под носки отдельный слот, имеющий свой слой. В добавок, решил разнообразить игру новыми видами носков, и небольшими фишками что с ними связаны.

## Медиа
![image](https://github.com/Workbench-Team/space-station-14/assets/143713810/c9c47003-3890-45cd-8311-c658f86f97e7)

**Чейнджлог**
🆑 Tamioki

- remove: Удалена старая система носков.
- add: Добавлено 31 новый вид раскраса носков, не включая по 2-3 вариаций длинны каждого из раскрасов.
- add: Добавлен новый тип слота одежды под носки.

2023-09-13 20:14 UTC, Mr0maks commented on Content.Shared/Inventory/SlotFlags.cs
> +    SOCKS = 1 << 1,
Носки обязательно должны быть первыми в этом enum?

2023-09-13 21:08 UTC, ITamiokiI commented on Content.Shared/Inventory/SlotFlags.cs
> +    SOCKS = 1 << 1,
В общем-то - нет. Они там из-за процесса моих экспериментов, в которых я пытался найти слои отображения. Как понятно - Они не тут. А остались они тут вот так, потому что я забыл их после того как нашёл нужный файл, переместить на место. Да и вроде, оно особо не на что не влияет.

2023-09-14 19:29 UTC, Mr0maks requested changes
Вообще ещё одно замечание: Для глав предметы можно убрать в из специальные мешки для вещей.

2023-09-14 19:29 UTC, Mr0maks commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +      - id: ClothingBeltChiefEngineerFilled
Странная строчка

2023-09-15 13:59 UTC, Mr0maks requested changes

2023-09-15 13:59 UTC, Mr0maks commented on Resources/Prototypes/Entities/Clothing/Under/will be filled out when implemented -S.txt
Удали этот файл вообще.

2023-09-15 14:00 UTC, Mr0maks commented on Resources/Prototypes/Entities/Clothing/Under/will be filled out when implemented -S.txt
Из за него падает rsi.diff

2023-09-15 14:17 UTC, Mr0maks requested changes

2023-09-15 14:17 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Не относится к данному пру. Откатить.

2023-09-15 14:41 UTC, AruMoon commented on Resources/Prototypes/Entities/Clothing/Under/will be filled out when implemented -S.txt
В том то и прикол что он падает как раз из-за того что он был удалён. Его уже удалили из апстрима. Название файла только верни оригинал, без расширения .txt. Тогда тест пройдёт

2023-09-15 16:05 UTC, Mr0maks commented on Resources/Prototypes/Entities/Clothing/Under/will be filled out when implemented -S.txt
> В том то и прикол что он падает как раз из-за того что он был удалён. Его уже удалили из апстрима. Название файла только верни оригинал, без расширения .txt. Тогда тест пройдёт

Да как то без разницы, пусть удалит типо и я его приму.

2023-09-15 17:58 UTC, AruMoon commented on Resources/Prototypes/Entities/Clothing/Under/will be filled out when implemented -S.txt
Я же сказал, удаление не поможет

2023-09-16 13:01 UTC, ITamiokiI commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Проблема в том, что кажется, файл уже откачен. Его видимо снова автоматом добавило. Я сравнил файлы с Репозитория АруМуна, и свой, и тот что в ПР-е, они одинаковы(По крайней мере, я не нашёл изменений, особенно с тем изменениями, что казаны в ПР-е.). Единственная проблема что осталась, это то что нельзя заполнить почему-то мешки с вещами Глав, носками. Скорее всего из-за вайтлиста, или места не хватает. Буду исправлять.

2023-09-16 13:55 UTC, Mr0maks approved these changes

2023-09-16 14:24 UTC, AruMoon requested changes
- Уменьши вместимость носков
- Добавь носки шахтёрам

2023-09-16 14:24 UTC, AruMoon commented on Resources/Prototypes/Entities/Clothing/Socks/base_clothingsocks.yml
> +    capacity: 5
Лучше уменьшить вместимость

2023-09-16 14:24 UTC, AruMoon commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
> +    - suitStorage
Изменения не относятся к ПРу

2023-09-16 18:41 UTC, AruMoon approved these changes

2023-09-16 18:43 UTC, merged