Modsuits is real
Workbench-Team/space-station-14 pull request #258
Opened 2023-09-25 22:30 UTC by Wizard-Grin

## О запросе слияния
Моды реальны! Пока система хромая, но в следующем пре обещает стать лучше. Производство сравнимо с рипли, но вот спецификация модов производится через g меню.
## Почему / Баланс
Множество раз было упомянуто, что моды являются альтернативой ригов, а может даже и лучше их! Можно попробовать поиграть с ними, в качестве эксперимента, к тому же это является хорошей базой для будущих наработок.

## Техническая информация

## Медиа

![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/f7c1e685-7e99-49f3-be04-acecf815c8d3)

**Чейнджлог**

:cl:
- add: Добавлено множество модсьютов! Подробнее в разделе гайдов.

2023-09-25 23:08 UTC, Barbatros commented
Ван клоузед реквест

2023-09-25 23:08 UTC, Barbatros commented
![IMG_20230925_030714_862](https://github.com/Workbench-Team/space-station-14/assets/132225998/8e35877b-f91b-48d9-963c-faa83793e58a)

2023-09-26 15:35 UTC, Wizard-Grin commented
Все подробности по модам есть ещё в разделе гайдов, вместе с видосом сборки

2023-09-26 18:45 UTC, AruMoon commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mech_construction.yml
> +# ModSuit Core
Эм чё? Почему моды в списке прототипов построения мехов?

2023-09-26 18:46 UTC, AruMoon commented on Resources/Prototypes/Entities/Objects/Specific/Mech/mech_construction.yml
> +# ModSuit Core
Можно же вынести в отдельный файл, а не пихать к мехам

2023-09-26 18:49 UTC, AruMoon commented on Resources/Prototypes/Research/industrial.yml
> +  cost: 15000
Изменение не в рамках данного пулл реквеста

2023-09-26 18:50 UTC, AruMoon requested changes
Вынеси конструкцию модов в отдельный файл от мехов

2023-09-26 18:50 UTC, Wizard-Grin commented on Resources/Prototypes/Research/industrial.yml
> +  cost: 15000
Не туда жмал когда цену меня. Исправил, должны были моды 15к стоить

2023-09-26 18:59 UTC, Wizard-Grin commented
Готово

2023-09-26 18:59 UTC, AruMoon commented
> Готово

Папку тоже другую. А то оно всё равно в папке мехов находится

2023-09-26 19:20 UTC, AruMoon approved these changes

2023-09-26 20:08 UTC, merged