Респрайт экипировки Офицера синего щита. Добавление новой экипировки для него, и исправление ошибок.
Workbench-Team/space-station-14 pull request #266
Opened 2023-09-27 17:29 UTC by ITamiokiI

## О запросе слияния
**Изменены части текстур экипировки Офицера синего щита:**
Шкаф офицера синего щита.
Рюкзак/Сумка/Вещмешок офицера синего щита.
Гарнитура офицера синего щита. (Обе.)
Комбинезон офицера синего щита.
КПК офицера синего щита.

**Изменены характеристики у скафандра Офицера синего щита.**

**Добавлена новая экипировка и вещи для Офицера синего щита:**
Плащ/Мантия офицера синего щита.
Водолазка офицера синего щита.
Юбка-комбинезон офицера синего щита.
Фигурка офицера синего щита.
Носки/Гольфы офицера синего щита.
Энергетический синий щит.
**Часть вещей добавлена в экипировку Офицера синего щита.**

**Изменена локализация некоторых предметов:**
Гарнитура командования(Та что ОСЩ) > Гарнитура синего щита.
Исправлены пару описаний у вещей ОСЩ.
Исправлена ошибка с "Меховыми носками", когда их айди в локализации было перепутано, и перевод не работал. (Всё  одной файле с носками, по этому это в одном Пре.)

## Почему / Баланс
Мне просто не понравились текстуры, они выглядели блекло, и в целом не очень вызывали положительных эмоций. По этой причине, решил сделать ретекстур части из них, на основе текстур TGstation.

Изменена локализация на более подходящую, в связи с тем, что некоторые названия и описания звучали нелогично, или неприятно на слух.

Характеристики скафандра были изменены для большего баланса, и цитирую - "Раундстартом скаф ОБР на станции".
Добавлен щит для ОСЩ в связи с тем что он не имеет абсолютно никаких особых вещей экипировки, не считая оружие, которое... Очень странное. А щит - И логично, и полезно, и пафосно, вполне символично.

Остальные предметы экипировки, представляющие из себя одежду, были добавлены для замены Капитанских вещей, что сейчас находятся в экипировке Офицера синего щита.

Фигурка ради Fun и коллекции. 

## Медиа
![image](https://github.com/Workbench-Team/space-station-14/assets/143713810/a50ded6f-66cd-4a41-a1f7-f84bde77ea69)

**Чейнджлог**

:cl: Tamioki
- tweak: Изменена часть спрайтов для экипировки и вещей Офицера синего щита. 
- tweak: Изменены характеристики скафандра Офицера синего щита.
- fix: Исправлена локализация обеих гарнитур Офицера синего щита. Так же отредактирована часть описаний.
- fix: Исправлена локализация Меховых носков.
- fix: Вещи капитана в снаряжении Офицера синего щита, заменены на его собственные!
- add: Добавлена новая экипировка и вещи для Офицера синего щита. Плащ/мантия, носки/гольфы. Юбка-Комбинезон, водолазка.
- add: Добавлен Синий энергетический щит.
- add: Синий энергетический щит добавлен в экипировку Офицера синего щита.
- add: Добавлена фигурка Офицера синего щита, для fun.

2023-09-29 18:38 UTC, Mr0maks submitted a review, later dismissed

2023-09-29 18:38 UTC, Mr0maks commented on Resources/Textures/Markers/jobs.rsi/blueshield.png
Как я помню для работ используются персонажи одетые в одежду. Возможно стоит вытащить данную текстуру откуда то?

2023-09-29 18:40 UTC, ITamiokiI commented on Resources/Textures/Markers/jobs.rsi/blueshield.png
Посмотри текстуру Боксёра и музыканта.(У одного просто перчатки, у второго саксафон.). Но если нужно, я могу сделать там и одетого полноценного персонажа.

2023-09-30 09:50 UTC, DjfjdfofdjfjD requested changes
Ну с локалью беда есть

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/shields/shields.ftl
> +    .desc = Продвинутый энергетический синий щит, в сложенном состоянии может поместиться даже в кармане.
Название странное, а описание не очень. Я бы добавил что-нибудь про реверс-инжиниринг щитов синдиката, аналог всё таки

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/under/under.ftl
> +    .desc = Стильные и дорогие гольфы, для защиты от холода ног, того, кто защищает глав станции.
Запятая перед "того" лишняя

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Модный и при этом странный плащ, для хранителя безопасности глав станции. Зачем он ему нужен? Конечно же, чтобы выглядеть стильно.
Перегруженное первое предложение, но окей. После "плащ" запятую бы убрать ещё

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpskirts.ftl
> +    .desc = Белая и приятная водолазка, для серьёзной работы, или серьёзного отдыха, которого у вас никогда не будет.
Лучше закончить предложение после "водолазка", пусть про отдых будет в отдельном. Запятая перед "или" не нужна

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Белая и приятная водолазка, для серьёзной работы, или серьёзного отдыха, которого у вас никогда не будет.
Такая же история

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/figurines.ftl
> +    .desc = Фигурка, представляющия собой офицера синего щита, строгого и синего, стоит на страже руководства станции. Наверное.
ПредставляющАя.
Я бы перефразировал вторую часть:
Синий и строгий, стоящий на защите руководства станции. Наверное.

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +  - type: Armor
Можно чутка побольше прописать взамен на большее замедление

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Prototypes/Entities/Objects/Shields/shields.yml
> +  parent: BaseItem
Разве нужно было писать с нуля? Не проще парентом щит синдиката указать?

2023-09-30 09:50 UTC, DjfjdfofdjfjD commented on Resources/Textures/Clothing/Back/Backpacks/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
Андерстендбл, хэв э найс дей

2023-09-30 10:13 UTC, ITamiokiI commented on Resources/Textures/Clothing/Back/Backpacks/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
Ну, можно указать Арсика, в мете, где уже не его текстурка.

2023-09-30 10:13 UTC, ITamiokiI commented on Resources/Prototypes/Entities/Objects/Shields/shields.yml
> +  parent: BaseItem
Ну, в целом можно. Но я тогда ещё не шарил за это.

2023-09-30 10:14 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/figurines.ftl
> +    .desc = Фигурка, представляющия собой офицера синего щита, строгого и синего, стоит на страже руководства станции. Наверное.
К. Гляну.

2023-09-30 10:14 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Белая и приятная водолазка, для серьёзной работы, или серьёзного отдыха, которого у вас никогда не будет.
К. Гляну.

2023-09-30 10:14 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpskirts.ftl
> +    .desc = Белая и приятная водолазка, для серьёзной работы, или серьёзного отдыха, которого у вас никогда не будет.
Гляну.

2023-09-30 10:14 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Модный и при этом странный плащ, для хранителя безопасности глав станции. Зачем он ему нужен? Конечно же, чтобы выглядеть стильно.
Гляну.

2023-09-30 10:14 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/under/under.ftl
> +    .desc = Стильные и дорогие гольфы, для защиты от холода ног, того, кто защищает глав станции.
Хорошо, гляну.

2023-09-30 10:14 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/shields/shields.ftl
> +    .desc = Продвинутый энергетический синий щит, в сложенном состоянии может поместиться даже в кармане.
Позже обсудим. Гэ

2023-10-18 10:01 UTC, MilenVolf requested changes
Узор на открываемом КПК поправить и исправь копирайты в фалах `meta.yml`. А в целом думаю пойдёт.

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Devices/pda.yml
Раз уж респрайт КПК, то думаю надо бы поправить и полосы в отображаемом КПК при его открытии. Смотри ниже в `- type: PdaBorderColor`

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Back/Backpacks/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
Не нужно так писать в авторстве. Поправь на нормальный вариант

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Back/Duffels/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
Тут тоже

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Back/Satchels/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
И тут нормально пожалуйста

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Ears/Headsets/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
И тут...

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Neck/Cloaks/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
Тут тоже...

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Neck/mantles/bsmantle.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
...Почему?...

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Under/Socks/blueshield_knee.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
...И тут...

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Under/Socks/blueshield_thigh.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
И тут

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
И тут

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/blueshield_turtleneck.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
И тут

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/blueshield.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
И тут.

2023-10-18 10:01 UTC, MilenVolf commented on Resources/Textures/Clothing/Uniforms/Jumpsuit/blueshield_turtleneck.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
И тут

2023-10-18 16:57 UTC, MilenVolf commented on Resources/Prototypes/Roles/Jobs/Command/blueshield.yml
> +  innerclothingskirt: ClothingUniformJumpskirtBlueshield
```suggestion
  innerClothingSkirt: ClothingUniformJumpskirtBlueshield
```

2023-10-18 16:59 UTC, MilenVolf commented
Поправь ченджлог

2023-10-19 09:42 UTC, MilenVolf commented on Resources/Textures/Clothing/Under/Socks/blueshield_knee.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
Тут забыл

2023-10-19 09:43 UTC, MilenVolf commented on Resources/Textures/Clothing/Under/Socks/blueshield_thigh.rsi/meta.json
> +  "copyright": "Meow, Tamioki",
Не исправил

2023-10-19 10:48 UTC, MilenVolf approved these changes

2023-10-19 14:47 UTC, merged