RD new tools
Workbench-Team/space-station-14 pull request #267
Opened 2023-09-27 21:12 UTC by Wizard-Grin

## О запросе слияния
Были добавлены новые инструменты для научного руководителя, а именно сканер и пинпоинтер.

## Почему / Баланс
Научный директор не имел особенных предметов, кроме портативного телепорта, который в основном уходи на общественное использование. Сканер имеет пониженный дуафтер, пинпоинтер изменен на большую дистанцию, он не будет вести до аномалии "в упор". Система аномалий была ухудшена, в связи с чем работа с ними приводит к нудному поиску по всей станции. Порой аномалию тяжело найти на маленькой станции, не говоря уже об огромных. К тому же система ивента спавна аномалии стала слишком частой, из-за этого непосещаемые зоны станции зачастую подвергаются разрушению той, или иной аномалии. А порой ЕМП взрывает часть станции из места, где никого не было.

**Чейнджлог**

:cl:
- add: Добавлен сканер научного руководителя, имеющий пониженный дуафтер.
- add: Добавлен кейс научный кейс, в котором содержатся все инструменты РД, включая телепортер.
- add: Добавлен пинпоинтер аномалий, эксклюзивно для РД.
- fix: Исправлено веселье!

2023-09-28 02:02 UTC, MilenVolf commented
Раз аномалии слишком часто появляются ивентом, может просто уменьшить шанс на этот ивент? У РнД есть ветка на изучение инструментов для обнаружения аномалий, тот же детектор. Он по сути станет бесполезным, так как НР будет либо сам бегать за аномалиями, либо давать навигатор кому-то из учёных, кто ими займётся. Станет он бесполезным не только потому что навигатор по сути бесконечен, а детектору нужна батарейка, но и куда удобнее и проще находит аномалии

2023-09-28 04:54 UTC, Wizard-Grin commented
>У РнД есть ветка на изучение инструментов для обнаружения аномалий, тот же детектор. Он по сути станет бесполезным. Станет он бесполезным не только потому что навигатор по сути бесконечен, а детектору нужна батарейка, но и куда удобнее и проще находит аномалии.
Этот локатор и так бесполезен, от слова совсем. Нет людей, которые им пользуются. Радиус в 20 тайлов совсем не помогает в ситуации.

2023-09-28 04:55 UTC, Wizard-Grin commented
> У РнД есть ветка на изучение инструментов для обнаружения аномалий, тот же детектор. Он по сути станет бесполезным,. Станет он бесполезным не только потому что навигатор по сути бесконечен, а детектору нужна батарейка, но и куда удобнее и проще находит аномалии.

Этот локатор и так бесполезен, от слова совсем. Нет людей, которые им пользуются. Радиус в 20 тайлов совсем не помогает в ситуации.

2023-09-28 04:57 UTC, Wizard-Grin commented
>Он по сути станет бесполезным, так как НР будет либо сам бегать за аномалиями, либо давать навигатор кому-то из учёных, кто ими займётся.

Так же можно сказать про снаряжение других глав. Гипо смо может заменить работу троих медиков, он просто может отдавать ее им, чтобы они лечили. Так же с поясом Си. Пробовал сделать ее на батарейке, вечные приколы с визуализатором не позволили это сделать.

2023-09-28 05:01 UTC, Wizard-Grin commented
> Тоже самое касается и Шимпа

Шимп является замечательной вещью, которую никто не крафтит, ибо открывается она на т2 за 10к. К этому времени уже стоит стабильно аномалия, либо очки вовсе не требуются. Помогать на таком позднем этапе изучения рнд он уже не в силах. Дать его раундстартом РД будет показательным экспериментом. С таким же успехом можно забрать продвинутые инструменты у СИ, ведь все его вещи так же крафтитяся.

2023-09-28 05:19 UTC, MilenVolf commented
> > Тоже самое касается и Шимпа
> 
> Шимп является замечательной вещью, которую никто не крафтит, ибо открывается она на т2 за 10к. К этому времени уже стоит стабильно аномалия, либо очки вовсе не требуются. Помогать на таком позднем этапе изучения рнд он уже не в силах. Дать его раундстартом РД будет показательным экспериментом. С таким же успехом можно забрать продвинутые инструменты у СИ, ведь все его вещи так же крафтитяся.

Я тоже об этом подумал, но у СИ спектр направленности использования инструментов другой. Про улучшенную версию анализатора аномалий я молчу, но про продвинутые инструменты... Аномалии это событие и обычно в количестве 1-2 максимум, что позволяет снарядить одного учёного этими инструментами и забыть про них. В то время как СИ с РСУ занимается быстрой заделкой повреждений, а инструментами активно оперировать для постройки/разборки большого количества конструкций за раз.

Насчёт исследований, их надо будет потом переработать под список из исследований с определёнными требованиями ( по типу как раньше было). Роллить их совсем неудобно

2023-09-28 05:22 UTC, MilenVolf commented
Давно я в РНД не бегал. Надо будет попробовать. Но тот факт, что изучать технологии стало крайне неудобно, это факт

2023-09-28 05:23 UTC, Wizard-Grin commented
Заниматься полной переработкой снаряжения рнд будет запарно, чтобы опять все было в мнимых рамках "баланса". На больших картах очень тяжело искать аномалии, особенно когда в многих местах плохая проходимость. Поисковик просто убирает рутинную часть игры рнд, которой не присутствует в других отделах. К тому же, аномалии быстро дистабилизируются, из-за чего поддерживать их становится невозможно (если показатель падает на "распадается", аномалия закроется через 2-3 импульса, даже если переводить ее обратно в "стабильное" положение). Поиграв 2 дня на РД стало понятно, что это просто утомляет. Большинство случаев, когда рнд все изучает, зависит от тупой рулетки, распадется ли аномалия, или нет.

2023-09-28 05:25 UTC, Wizard-Grin commented
Даже с фулловой аномалией можно фармить ~70-80 очков в сек. Для фулл изучения рнд надо ~340k. Если переводить это в секунды, получится 1ч, только на то, чтобы открыть, не применять в игре. Но аномалия не может прожить 1ч, как бы игрок не старался. Период жизни ~10-15 минут. В редких случаях 20. Из этого и выходит, что постоянная возня с аномалиями утомляет, а уж тем более на огромных картах.

2023-10-09 21:10 UTC, MilenVolf requested changes
Поправь название и локаль и думаю пока можно будет НРу с ШИМП'ом побегать. Потом, как затронем систему технологий, тогда поглядим.

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Textures/Objects/Devices/pinpointer.rsi/meta.json
> +            "name": "pinpointer_RD"
Думаю будет лучше переименовать в "pinpointer_anomaly", также спрайт переименовать

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
> +  id: PinpointerRD
Стоит переименовать в PinpointerAnomaly

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
> +    - state: pinpointer_RD
Не забудь тут также поменять название стейта

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
> +    targetName: Аномальную активность
Замени это переменной и перенеси в ftl

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pinpointer.ftl
> +ent-PinpointerRD = аномальный поисковой навигатор
"поисковый навигатор аномалий"
И не забудь переименовать "ent-PinpointerRD" на "ent-PinpointerAnomaly"

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pinpointer.ftl
> +ent-PinpointerRD = аномальный поисковой навигатор
```suggestion
ent-PinpointerAnomaly = поисковой навигатор аномалий
```

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
> +  id: PinpointerRD
```suggestion
  id: PinpointerAnomaly
```

2023-10-09 21:10 UTC, MilenVolf commented on Resources/Textures/Objects/Devices/pinpointer.rsi/meta.json
> +            "name": "pinpointer_RD"
```suggestion
            "name": "pinpointer_anomaly"
```

2023-10-10 12:43 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
> +    targetName: Аномальную активность
Как я тебе таргет нейм перенесу в переменную

2023-10-10 14:29 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
> +    targetName: Аномальную активность
> Как я тебе таргет нейм перенесу в переменную

В переменную для локали. В ftl

2023-10-10 16:37 UTC, MilenVolf approved these changes

2023-10-10 16:55 UTC, merged