MiniJoke)
Workbench-Team/space-station-14 pull request #27
Opened 2022-12-19 17:52 UTC by Cooderer

Ochen smeshno, rjomba 3000

## About the PR 

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!

2022-12-19 17:54 UTC, DjfjdfofdjfjD commented
Micropizdricjoke

2022-12-20 08:11 UTC, PilgrimViis commented
Кто-то очень не любит СБ. ^_^

2022-12-20 09:09 UTC, PilgrimViis requested changes

2022-12-20 09:09 UTC, PilgrimViis commented on Resources/Prototypes/Entities/Objects/Fun/AruPlushie/hmgsCap.yml
> +    capacity: 1000
Может сделать 100, как у обычного пулемёта? Слишком много.

2022-12-20 09:09 UTC, PilgrimViis commented on Resources/Prototypes/Entities/Objects/Fun/AruPlushie/hmgsCap.yml
> +    fireRate: 15
У L6 пулемёта он 8. По идее это хорошо, т.к. звук должен быть другой. Надо проверить.

2022-12-20 09:10 UTC, PilgrimViis commented on Resources/Prototypes/Entities/Objects/Fun/AruPlushie/hmgsCap.yml
> +    capacity: 1000
Ну или 200, т.к. firerate выше.

2022-12-20 09:36 UTC, CaptainSqrBeard commented
https://github.com/space-wizards/space-station-14/pull/12591
Лучше уж тогда вот это до ума довести

2022-12-20 10:56 UTC, Mr0maks commented
> [space-wizards#12591](https://github.com/space-wizards/space-station-14/pull/12591) Лучше уж тогда вот это до ума довести

Не вижу смысла делать ещё больше пластмассовых стаканчиков для сб. Им уже хватает меча с пистоновым пистолетом :)

2022-12-20 11:32 UTC, CaptainSqrBeard commented
> > [space-wizards#12591](https://github.com/space-wizards/space-station-14/pull/12591) Лучше уж тогда вот это до ума довести
> 
> Не вижу смысла делать ещё больше пластмассовых стаканчиков для сб. Им уже хватает меча с пистоновым пистолетом :)

Они дартами, а не пистонами стреляют. Так-что СБ не должны так тупить. Там ещё так-же есть риот дарты для трейторки которые урон по стамине наносят

2022-12-20 12:45 UTC, merged