Syndicate SWAG update
Workbench-Team/space-station-14 pull request #273
Opened 2023-09-29 17:14 UTC by quartuG3

## О запросе слияния
Добавлены 3 вида балаклав с ТГ. Добавлен СиндиШкаф в аплинк. Добавлены балаклавы в позиции ОдеждоМата и СиндиШкафа. При использовании ЕМАГа на СиндиШкаф - в его каталог будет добавлен один противогаз синдиката. При взломе ОдеждоМата - в его каталог будут добавлены 3 балаклавы.

**Чейнджлог**

:cl: Quartug
- add: Добавлен СиндиШкаф в аплинк.
- add: Добавлены балаклавы.

2023-09-29 18:46 UTC, Mr0maks requested changes

2023-09-29 18:46 UTC, Mr0maks commented on Resources/Textures/Clothing/Mask/rusbalaclava.rsi/meta.json
> +  "license": "CC-BY-NC-SA 3.0",
```Resources/Textures/Clothing/Mask/rusbalaclava.rsi: meta.json: [$.license] 'CC-BY-NC-SA 3.0' is not one of ['CC-BY-3.0', 'CC-BY-4.0', 'CC-BY-SA-3.0', 'CC-BY-SA-4.0', 'CC-BY-NC-3.0', 'CC-BY-NC-4.0', 'CC-BY-NC-SA-3.0', 'CC-BY-NC-SA-4.0', 'CC0-1.0']```

```CC-BY-NC-SA 3.0``` на ```CC-BY-NC-SA-3.0```

2023-09-30 05:09 UTC, Mr0maks requested changes

2023-09-30 05:09 UTC, Mr0maks commented on Resources/Textures/Clothing/Mask/rusbalaclava.rsi/meta.json
> +  "license": CC-BY-NC-SA-3.0",
```  "license": CC-BY-NC-SA-3.0",``` Опять ошибка. Пропущена скобка.

2023-10-03 12:34 UTC, Mr0maks approved these changes

2023-10-03 12:36 UTC, Mr0maks requested changes

2023-10-03 12:36 UTC, Mr0maks commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/syndiedrobe.yml
> -    ClothingUnderSocksWhiteStockings: 4
Какой смысл удаления?

2023-10-03 13:20 UTC, quartuG3 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/syndiedrobe.yml
> -    ClothingUnderSocksWhiteStockings: 4
А есть ли смысл для белых чулок в емагнутом Синдишкафе? Было бы больше смысла, если бы это были черные. Но белые чулки в нем - странно

2023-10-18 10:05 UTC, MilenVolf commented
Откроем как только ты вернёшься к пр-у и исправишь конфликты.

2023-10-18 10:05 UTC, closed without merging