More traits
Workbench-Team/space-station-14 pull request #281
Opened 2023-10-06 01:45 UTC by Pingvas

## О запросе слияния
Никто не просил, но теперь оно есть

## Почему / Баланс
Толерантность к алкоголю -> Не отменяет действие этанола т.е. не робаст.
Ня акцент -> Ну уж очень хочется кошек.

## Техническая информация
А ничего и не сломается...

## Медиа

- [Х] Я добавил скриншоты/видео к этому запросу слияния, демонстрирующие его изменения в игре, **или** этот запрос слияния не требует демонстрации в игре

**Чейнджлог**

:cl: Pingva
- add: Добавлены черты характера.

2023-10-06 04:42 UTC, MilenVolf requested changes
Насчёт возможности выбора акцента Мяуканья для всех не уверен, но было бы лучше, если бы выбрать его могли лишь Фелиниды.

2023-10-06 04:42 UTC, MilenVolf commented on Resources/Locale/ru-RU/administration/smites.ftl
> +admin-smite-felinid-species-swap-description = Меняет ксеновид на Фелинада. Мяу!
*Фелинида

2023-10-06 04:42 UTC, MilenVolf commented on Content.Shared/Drunk/DrunkSystem.cs
> +
По-хорошему, их бы объединить

2023-10-06 04:42 UTC, MilenVolf commented on Content.Shared/Traits/Assorted/HardweightDrunkComponent.cs
Думаю будет лучше объединить этот компонент с легкопьяницей, вместо того, чтобы создавать новый.

2023-10-06 04:42 UTC, MilenVolf commented on Resources/Locale/ru-RU/traits/traits.ftl
> +trait-hardweight-name = Алкогольный тяжеловес
Как насчёт варианта "Бывалый пьянчуга"? Не обязательно, просто как вариант.

2023-10-06 04:42 UTC, MilenVolf commented on Resources/Prototypes/Traits/inconveniences.yml
> +      boozeHardStrengthMultiplier: 0.2
Не чересчур ли большой резист? Человек быстрее умрёт от алкогольного отравления, нежели станет пьяным.

2023-10-06 04:42 UTC, MilenVolf commented on Resources/Prototypes/Traits/neutral.yml
> +
Я не уверен, стоит ли давать возможность всем расам выбрать этот акцент. Было бы лучше, если бы его могли брать только Фелиниды

2023-10-06 12:52 UTC, Pingvas commented on Content.Shared/Drunk/DrunkSystem.cs
> +
> По-хорошему, их бы объединить

Я всячески пытался... Только такой вариант с разделением подходит

2023-10-08 21:50 UTC, MilenVolf commented on Resources/Locale/en-US/traits/traits.ftl
> +trait-nya-accent-name = Nya!
Убери тут неиспользованную локаль и пойдёт

2023-10-14 14:48 UTC, Pingvas commented
@MilenVolf ну чё там с пром?

2023-10-14 21:30 UTC, MilenVolf commented
> @MilenVolf ну чё там с пром?

У тебя 2 ПР-а в одном по сути

2023-10-14 21:43 UTC, MilenVolf commented on Resources/Locale/ru-RU/traits/traits.ftl
> +trait-hardweight-name = Алкогольный тяжеловес
Может тогда Устойчивость к алкоголю? Тяжеловес, как мне кажется, немного странновато звучит

2023-10-15 05:39 UTC, AruMoon commented
Люди, разделяйте разные изменения в разные пулл реквесты

2023-10-18 09:38 UTC, MilenVolf commented
Не думаю трейт на устойчивость к алкоголю сейчас нужен. По крайней мере пока.

2023-10-18 09:38 UTC, closed without merging