Обновление ветки СБ в рнд + возможность крепить оружие
Workbench-Team/space-station-14 pull request #286
Opened 2023-10-11 22:43 UTC by Wizard-Grin

## О запросе слияния
Данный пулл реквест добавляет возможности прикреплять оружие разного "размера" к определенным креплениям, подробнее на скриншотах.
Помимо этого переработана ветка сб в изучениях, возвращены огнестрельные технологии, а так же пересмотрено использование фабрикатора боеприпасов и оружиейного техфаба.

## Почему / Баланс
Крепления присутствуют в 13 и позволяют разнообразить геймплей, посредствам освобождения места в инвентаре. Многие оружия не имели достойного внимания, такие как лектер или лазерный карабин, ибо занимали много места и ничего не могли противопоставить другому оружию. 
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/8bf6cb48-4aef-433e-954e-80293a39eb3d)
В рнд возвращены огнестрельные технологии, а так же пересмотрено содержание фабрикаторов патрон и оружия.
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/a05688d9-c6d4-471a-b94a-a73ca515585e)
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/45c35e22-6e0c-40b0-9c4e-dcbeb37a6d86)
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/8231c6da-18a1-4e0b-af18-0455c620991f)
В охранфаб добавлена возможность производства брони и разгрузок для СБ.
## Техническая информация

## Медиа
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/51f9535d-0e32-4371-8203-96f0651d7de7)
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/5c91c9b8-c843-4dd0-b33b-98733f912d51)

:cl:
- add: Добавлены оружейные технологии в ветку сб рнд.
- add: Добавлены расширенные магазины для Лектора и вектора.
- add: Добавлен МК68.
- tweak: Изменено содержание техфабов сб.
- tweak: Возвращен вектор. Имеет калибры .20 и .35.

2023-10-11 23:18 UTC, MilenVolf requested changes
Поправь также описание на английском у самого модифицированного оружия в прототипах.
Ну и ещё у тебя разнятся локали английские и русские у mk68.

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/smgs/smgs.ftl
> +    .desc = Нестандартный пистолет пулемёт, имеющий возможность стрелять двумя калибрами. Использует патроны калибра .35 и .20.
Дефис у "пистолет-пулемёт" оставь

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
НИКОГДА не допускай кириллицы в прототипах. Делай ftl-переменные. У других слотов они имеются

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
Тут тоже самое

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
И тут

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/smgs/smgs.ftl
> +    .desc = Нестандартный пистолет пулемёт, имеющий возможность стрелять двумя калибрами. Использует патроны калибра .35 и .20.
А также, меняя локаль на русском под актуальный вариант особенности оружия, надо также в самом прототипе в его описании.

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Locale/en-US/research/technologies.ftl
Обновляй оба файла локали, а не только русский.

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
> +  name: mk 58
mk 68

2023-10-11 23:18 UTC, MilenVolf commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
> +  description: A cheap, ubiquitous sidearm, produced by a NanoTrasen subsidiary. Uses .35 auto ammo.
Описание разнится с тем, что в файле русской локали. (Английскую локаль создавать не обязательно, так как её создаст скрипт)

2023-10-11 23:20 UTC, Wizard-Grin commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/smgs/smgs.ftl
> +    .desc = Нестандартный пистолет пулемёт, имеющий возможность стрелять двумя калибрами. Использует патроны калибра .35 и .20.
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/b115ba22-cf44-418e-83a9-0d04081262d7)

2023-10-11 23:21 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
![image](https://github.com/Workbench-Team/space-station-14/assets/100096262/c47bfbf6-dd86-4146-901d-39d634aee563)
Че правда имеются?

2023-10-11 23:22 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
Выше ответил, ошибок не выдёт. Как сяду полную локализацию делать, тогда исправлю. Пока что это будет единичным тыком, остальное тоже прейдется менять.

2023-10-11 23:22 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
Выше ответил, ошибок не выдёт. Как сяду полную локализацию делать, тогда исправлю. Пока что это будет единичным тыком, остальное тоже прейдется менять.

2023-10-11 23:22 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        name: Оружейная кобура
Выше ответил, ошибок не выдёт. Как сяду полную локализацию делать, тогда исправлю. Пока что это будет единичным тыком, остальное тоже прейдется менять.

2023-10-11 23:22 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        name: Оружейная кобура
Выше ответил, ошибок не выдёт. Как сяду полную локализацию делать, тогда исправлю. Пока что это будет единичным тыком, остальное тоже прейдется менять.

2023-10-11 23:24 UTC, Wizard-Grin commented on Resources/Locale/en-US/research/technologies.ftl
Я не наблюдаю, чтобы остальные следовали данным требованиям, либо с них это спрашивали. Добавленные крысой мехи и арбалет не был ревьюйнут на английскую фтл.

2023-10-11 23:26 UTC, Wizard-Grin commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
> +  name: mk 58
Исправил

2023-10-12 01:03 UTC, MilenVolf approved these changes

2023-10-12 04:37 UTC, merged