Небольшой реворк и ретекстур Бригмедика, и добавление его обратно в игру, вместе с новой экипировкой.
Workbench-Team/space-station-14 pull request #305
Opened 2023-10-31 22:34 UTC by ITamiokiI

# О запросе слияния

##**Добавлена должность Бригмедика обратно, вместе с переработанной экипировкой. **
А так же добавлены/изменены лазареты брига под все нужды на каждой станции (Кроме Packed, где это не оказалось возможным.)

##**Изменены:**
**Спрайты всей одежды у Бригмедика, кроме его Гарнитуры;**
Сумка, Рюкзак, Вещмешок, Берет, Комбинезоны, Бронированный халат, Военно-Медицинская маска, Скафандр, Медико-Охранный Визор.

**Изменён стартовый набор Бригмедика**

**Немного изменены характеристики скафандра Бригмедика** 
Он стал чутка быстрее, но слабее в защите (Почему медик был медленнее СБ?)

**Некоторые локали у затронутых выше предметов.**

**Спрайт спавна должности Бригмедика**

**Медико-Охранный визор наконец рабочий, и получил своё описание вместо "Заполнитель"**

##**Добавлены:**
**Медицинские солнцезащитные очки.**
Солнцезащитные очки с встроенным Med Hud-ом, защищающие от вспышек, и показывающие здоровье окружающих. Уникальный предмет Бригмедика, являющийся его стартовой частью набором экипировки.

**Новая экипировка для Бригмедика.**
Водолазки, Ветровка.

**По стандарту: Добавлена фигурка Бригмедика, 4fun**

# Почему / Баланс
Люди хотели(Я спрашивал). К тому же, Бригмедик, хорошая должность, которая уже у нас была, и многие были разочарованны её удалением (Хотя была удалена в связи с её недоработкой). По этому я посчитал, что нанимать Бригмедика из меда (Чего зачастую не происходит, ибо меда просто нет), с тем СРП что прописано у него (Со всеми этими условностями того, что он медик, и не часть СБ и просто был нанят) - Ну не очень. 
К тому же, очень хорошая должность, с интересным геймплеем полевого медика, который спасает своих товарищей в пылу сражения. (Или нет)

# Медиа
![Content Client_C4AamozVT9](https://github.com/Workbench-Team/space-station-14/assets/143713810/ce33a038-fee7-4a2c-901a-3b70994667d1)
![Content Client_lIa824tJMk](https://github.com/Workbench-Team/space-station-14/assets/143713810/648146e3-f0e5-43b1-968d-2d39e7dce425)
![Content Client_zaPdkrDVEq](https://github.com/Workbench-Team/space-station-14/assets/143713810/a4ad9245-df9e-4a95-a5e8-7f708bda2d97)
![Content Client_saq2Vm1no2](https://github.com/Workbench-Team/space-station-14/assets/143713810/b7289fbb-4a09-4862-b076-4024d5eb88cf)
![Content Client_QKNiT3mUl1](https://github.com/Workbench-Team/space-station-14/assets/143713810/1b709549-6af3-475b-872d-8d924ece474d)
![Content Client_wUelSI78jl](https://github.com/Workbench-Team/space-station-14/assets/143713810/67e308ed-85a6-4fd2-947b-c74498f338ee)

**Чейнджлог**
:cl: Tamioki
- tweak: Изменены все спрайты одежды Бригмедика.
- tweak: Изменены локали некоторых предметов Бригмедика.
- tweak: Изменены лазареты брига практически на каждой станции.
- tweak: Изменён Медико-Охранный визор. Теперь он работает правильно, и имеет описание.
- add: Добавлены медицинские солнцезащитные очки.
- add: Добавлена небольшая часть экипировки для Бригмедика.
- add: Добавлена должность Бригмедик. AAGH! MEDIC!
- add: Добавлена фигурка Бригмедика. 4Fun.

2023-11-01 17:58 UTC, DjfjdfofdjfjD requested changes

2023-11-01 17:58 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/back/backpacks.ftl
> +    .desc = Это очень стерильный и вместительный на вид рюкзак с стильной нашивкой ангельского-красного креста.
Со стильной, - убери

2023-11-01 17:58 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +    .desc = Военный респиратор защищающий от небольших повреждений глаз и заражения через дыхательные пути.
Стоит ли менять описание предмета который уже есть в игре?

2023-11-01 17:58 UTC, DjfjdfofdjfjD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/figurines.ftl
> +    .desc = Фигурка, представляющая собой бригмедика, бравого полевого медика сражающегося за жизни своих товарищей, даже под градом пуль и лучей лазерных винтовок.
Тире бы поставить вместо второй запятой

2023-11-01 18:18 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +    .desc = Военный респиратор защищающий от небольших повреждений глаз и заражения через дыхательные пути.
Вернул.

2023-11-01 18:18 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/figurines.ftl
> +    .desc = Фигурка, представляющая собой бригмедика, бравого полевого медика сражающегося за жизни своих товарищей, даже под градом пуль и лучей лазерных винтовок.
Исправил.

2023-11-01 18:18 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/back/backpacks.ftl
> +    .desc = Это очень стерильный и вместительный на вид рюкзак с стильной нашивкой ангельского-красного креста.
Исправил.

2023-11-03 15:17 UTC, MilenVolf requested changes
Поправь локаль, английские описания и копирайт мета-файла скафандра. А в целом всё остальное выглядит очень даже добротно.

2023-11-03 15:17 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/back/backpacks.ftl
> +    .desc = Это очень стерильный и вместительный на вид рюкзак с нашивкой ангельского-красного креста.
```suggestion
    .desc = Это очень стерильный и вместительный на вид рюкзак с нашивкой красного ангельского креста.
```

2023-11-03 15:17 UTC, MilenVolf commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/hud.ftl
> +    .desc = Объединение медицинского и охранного окуляров в одно целое для большей эффективности.
```suggestion
    .desc = Объединяет в себе функционал медицинского и охранного визоров для большей эффективности.
```

2023-11-03 15:17 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  description: Strangely ancient technology used to help provide rudimentary eye cover. Enhanced shielding blocks many flashes.
Описание с тем что на русском на совпадает.

2023-11-03 15:17 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
> +        Heat: 0.70
Нули можно и убрать в конце

2023-11-03 15:17 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +  description: This uniform is issued to qualified personnel who have been trained. No one cares that the training took half a day.
Тут тоже не совпадает

2023-11-03 15:17 UTC, MilenVolf commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +  description: This uniform is issued to qualified personnel who have been trained. No one cares that the training took half a day.
Тут тоже

2023-11-03 15:17 UTC, MilenVolf commented on Resources/Textures/Clothing/Head/Hardsuits/brigmedic.rsi/meta.json
Текстуры скафандра поменялись, а копирайт в мета-файле нет?

2023-11-03 15:42 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/back/backpacks.ftl
> +    .desc = Это очень стерильный и вместительный на вид рюкзак с нашивкой ангельского-красного креста.
Тут поправлю, окей.

2023-11-03 15:42 UTC, ITamiokiI commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/hud.ftl
> +    .desc = Объединение медицинского и охранного окуляров в одно целое для большей эффективности.
Ну тут я попытался скопировать описания других визоров, но хорошо.

2023-11-03 15:43 UTC, ITamiokiI commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  description: Strangely ancient technology used to help provide rudimentary eye cover. Enhanced shielding blocks many flashes.
Да, его и не видно, ибо локаль. У Воти так буквально со всеми прототипами было. Но хорошо, изменю.

2023-11-03 15:43 UTC, ITamiokiI commented on Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
> +        Heat: 0.70
Понял.

2023-11-03 15:44 UTC, ITamiokiI commented on Resources/Textures/Clothing/Head/Hardsuits/brigmedic.rsi/meta.json
Исправлю, забыл.

2023-11-04 14:40 UTC, MilenVolf approved these changes

2023-11-04 14:43 UTC, merged