lobbyscreens
Workbench-Team/space-station-14 pull request #323
Opened 2024-01-16 20:32 UTC by Ratyyy

## О запросе слияния

Добавила большинство лоббискринов с корвакса 
## Почему / Баланс

красиво.

## Медиа

- [X] Я добавил скриншоты/видео к этому запросу слияния, демонстрирующие его изменения в игре, **или** этот запрос слияния не требует демонстрации в игре

2024-02-01 21:21 UTC, MilenVolf requested changes
Фоны в общем-то неплохие, но некоторые лучше убрать как мне кажется. А ну и фоны что к рождеству относятся лучше убрать, ну может кроме Яо тащащего боеголовку, фон очень красивый и вписывается отлично.

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/arnold-intelligence.png
Не уверен насчёт этого фона. Выглядит довольно пусто и ну... это 3д.

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/lizard-bar.png
Выглядит довольно простенько? Не очень нравится стиль этого фона.

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/new-year-bar.png
Арт красивый, но уже не новый год и не рождество.

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/new-year-comfort.png
Рождество и новый год прошли.

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/new-year-explosion.png
Выглядит довольно интересно, но стиль не очень нравится. + Тут по сути иконка сервера корвакса

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/new-year-pine.png
Рождество и новый год прошли.

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/revenant.png
Понятия не имею как это относится к сс14. Может это босс лаваленда из 13-й? В данный момент такого существа нет в 14-й.

2024-02-01 21:21 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/you-look-lonely.png
Не думаю что стоит это ставить на фон. Снизу явно не фелинид.

2024-02-02 13:41 UTC, Ratyyy commented on Resources/Textures/LobbyScreens/revenant.png
это ревенант...

2024-02-02 20:07 UTC, MilenVolf commented on Resources/Textures/LobbyScreens/revenant.png
Не очень похож если честно

2024-02-09 11:50 UTC, MilenVolf approved these changes

2024-02-19 02:48 UTC, MilenVolf commented
Изображения теперь надо конвертировать в Webp.

2024-04-20 04:22 UTC, merged