Крафт маленького вентилятора
Workbench-Team/space-station-14 pull request #33
Opened 2022-12-20 12:04 UTC by PilgrimViis

Добавить крафт маленького вентилятора
by Desoth https://discord.com/channels/727015266642296924/1037396123985379338/1054708176005640212

![image](https://user-images.githubusercontent.com/6408195/208662897-d4756438-be7b-4dfe-bba0-05cfceda8d1b.png)

2022-12-20 12:34 UTC, Mr0maks requested changes

2022-12-20 12:34 UTC, Mr0maks commented on Resources/Prototypes/Recipes/Construction/Graphs/utilities/atmos_unary.yml
> +        amount: 1
Крафт слишком простой. Надо добавить усложнение для абуза.

2022-12-20 15:25 UTC, PilgrimViis commented on Resources/Prototypes/Recipes/Construction/Graphs/utilities/atmos_unary.yml
> +        amount: 1
Ээ, ну можно конечно, но это же простая штука. По сути все штуки из атмоса так крафтятся, в один шаг.

2022-12-20 15:36 UTC, Mr0maks commented on Resources/Prototypes/Recipes/Construction/Graphs/utilities/atmos_unary.yml
> +        amount: 1
> Ээ, ну можно конечно, но это же простая штука. По сути все штуки из атмоса так крафтятся, в один шаг.

Проблема в том что атмос вентилятор работает как галопроектор и не впускает и не выпускает газы. Позволяет так гриферить поэтому его надо сделать максимально нерабочим для грифа повысив ресурсы для крафта. Те кто уже делают шаттл не сильно заметят пропажу ресурсов а вот гриферам будет сложнее.

2022-12-20 19:55 UTC, PilgrimViis commented on Resources/Prototypes/Recipes/Construction/Graphs/utilities/atmos_unary.yml
> +        amount: 1
Ну да, именно поэтому он и полезная штука. А гриф в чем? Ограничить пространство между вентиляцией чтобы там воздуха не было?

2022-12-20 20:16 UTC, PilgrimViis commented on Resources/Prototypes/Recipes/Construction/Graphs/utilities/atmos_unary.yml
> +        amount: 1
Если всё таки усложнить, то чем усложнить? Редкими материалами или больше шагов крафта сделать?

2022-12-22 18:09 UTC, Mr0maks commented on Resources/Prototypes/Recipes/Construction/Graphs/utilities/atmos_unary.yml
> +        amount: 1
> Если всё таки усложнить, то чем усложнить? Редкими материалами или больше шагов крафта сделать?

Увеличить к примеру колличество необходимой стали, добавить схему к примеру, добавить пластик ещё. Много вариантов но нельзя давать возможность сделать из одного стула два вентилятора.

2023-01-27 10:06 UTC, closed without merging