Drinks cartons fix and weh & buzz update
Workbench-Team/space-station-14 pull request #357
Opened 2024-06-01 19:14 UTC by lAstronautl

## О запросе слияния
Маленький фикс картонных коробочек и добавление того что вех и бзз сок наносят яды.

## Почему / Баланс
Ну эээ так вроде баланснее и милен про это говорил так что вот.

## Медиа
![image](https://github.com/Workbench-Team/space-station-14/assets/85165800/7899a161-06bb-4e21-a248-c6df7071d763)
![image](https://github.com/Workbench-Team/space-station-14/assets/85165800/2ade02c9-3ac0-45d9-9538-618453e1be85)
![image](https://github.com/Workbench-Team/space-station-14/assets/85165800/79016e0a-791d-4a89-9e17-92ec859c873c)

**Чейнджлог**
:cl: Astr0naut
- tweak: Вех сок и бззз сок наносят урон ядами, будьте аккуратнее!
- fix: Исправлена локализация лимонного сока.

2024-06-02 09:13 UTC, MilenVolf commented
В СБмат не добавляй сок

2024-06-02 09:57 UTC, MilenVolf requested changes

2024-06-02 09:57 UTC, MilenVolf commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
> +    DrinkJuiceSecCarton: 1
Лучше уж тогда его вообще никуда не вставлять этот сок. Думаю лучше будет из него сделать напиток, а сок убрать вообще.

2024-06-02 10:13 UTC, lAstronautl commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
> +    DrinkJuiceSecCarton: 1
тогда согласен

2024-06-03 00:58 UTC, MilenVolf approved these changes

2024-06-03 01:00 UTC, merged