Locale add v2
Workbench-Team/space-station-14 pull request #366
Opened 2024-06-13 11:31 UTC by quartuG3

## О запросе слияния
Добавлен перевод лодауту ОСЩ и КЦК, а так же исправлены локали  для предметов ОСЩ и КЦК

## Почему / Баланс
Глаза мозолит.

## Медиа
![lodaut](https://github.com/Workbench-Team/space-station-14/assets/140832593/25bd4998-385f-4974-b7db-09c160288a76)

**Чейнджлог**
Слишком мало для чейнджлога.

2024-06-13 13:44 UTC, MilenVolf requested changes
Перенеси нашу локаль наших предметов в отдельную папку в `Locale/ru-RU/starshine` по аналогичному пути. Если папки таковой не будет, создай

2024-06-13 16:38 UTC, quartuG3 commented
Вопрос по локалям лодаутов: их тоже переносить?

2024-06-13 17:33 UTC, MilenVolf commented
> Вопрос по локалям лодаутов: их тоже переносить?
> 

Да, всё что было добавлено нами надо переносить.

2024-07-13 12:50 UTC, MilenVolf approved these changes

2024-07-13 13:33 UTC, merged