Uhuh, Sledgehammer
Workbench-Team/space-station-14 pull request #57
Opened 2023-02-19 00:51 UTC by PMCMidas

Йоу, в первый раз работаю с гитхабом, поэтому всё сделано криво. Это проваславная кувалда, которую нарисовал adadsa#5831 за что я ему ОЧЕНЬ благодарен!!

## About the PR

**Media**

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!

2023-02-19 01:23 UTC, Mr0maks requested changes
Нету стиля, файл находиться не там где надо.

2023-02-19 01:26 UTC, Mr0maks requested changes
Текстуры кувалды имеют странные названия, нету мета информации и текстуры расположены не там где надо.

2023-02-19 01:27 UTC, Mr0maks requested changes
Нету локализации.

2023-02-19 05:13 UTC, DjfjdfofdjfjD commented
Аряяя, в названии l вместо I!!!!

2023-02-19 05:41 UTC, AruMoon commented
> Аряяя, в названии l вместо I!!!!

Норм все вроде как

2023-02-28 13:36 UTC, AruMoon commented
#69

2023-02-28 13:36 UTC, closed without merging