Dual Energy Sword is real?
Workbench-Team/space-station-14 pull request #63
Opened 2023-02-22 07:58 UTC by DjfjdfofdjfjD

**У меча нет выключенного варианта, возможны проблемы с текстурами. _Возможность включать и выключать добавлю когда-нибудь потом_**
Энергетический меч в аплинке предателя и нюкеров, стоит 12 телекристаллов, нельзя выключить или положить в рюкзак, наносит сравнительно небольшой урон в одной руке, но в двух руках его урон становится гигантским.
- add: double energy sword in uplink

2023-02-22 08:06 UTC, DjfjdfofdjfjD commented
проверка провалена из-за лишних неиспользуемых текстур, это варианты выключенного меча, который на данный момент не сделан.

2023-02-22 08:08 UTC, CaptainSqrBeard commented
было-бы лучше если-бы это было больше похоже на есворд по механикам, чем на топор.

2023-02-22 08:12 UTC, DjfjdfofdjfjD commented
> было-бы лучше если-бы это было больше похоже на есворд по механикам, чем на топор.

к сожалению, у меня не получилось украсть код от обычного есворда, там тупо текстуры по другому сделаны, у них отдельны лезвие и рукоятка, так что функции выключения нет. Однако когда-нибудь я сделаю под свой вариант.

2023-02-25 12:00 UTC, DjfjdfofdjfjD commented
как я блин ненавижу текстурки, ужас, лучше бы в текст играли

2023-02-25 12:24 UTC, DjfjdfofdjfjD commented
оно готово!!!!!!!!

2023-02-28 14:23 UTC, AruMoon requested changes
Сделай его нормальным энергитическим мечом и сделай ему нормальный id

2023-03-10 13:58 UTC, closed without merging

2023-03-10 13:58 UTC, DjfjdfofdjfjD commented
переделаю позже.