Первый пр?
Workbench-Team/space-station-14 pull request #7
Opened 2022-12-09 21:05 UTC by Cooderer

Я смог?
тут 2 игрушки + добавление в список наград из аркады

2022-12-09 21:23 UTC, Mr0maks requested changes

2022-12-09 21:23 UTC, Mr0maks commented on Resources/Textures/Objects/Misc/toy_shlepa.rsi/meta.json
> +  "copyright": "For Aru",
Извени но надо указать авторство нормально

2022-12-09 21:23 UTC, Mr0maks commented on Resources/Textures/Objects/Misc/toy_dumpling.rsi/meta.json
> +  "copyright": "For Aru",
Тоже самое. Авторство надо указать нормально.

2022-12-09 21:23 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Fun/AruPlushie/toyShlepa.yml
> +  description: Where he was at 24th february
Думаю описание можно изменить более в нейтральное русло

2022-12-09 21:23 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Fun/AruPlushie/toyShlepa.yml
> +  name: Shlepa the war criminal
Тоже самое но и для имени. Более нейтральное.

2022-12-10 03:28 UTC, CaptainSqrBeard commented
Надо-бы файлы локализации добавить

2022-12-10 05:38 UTC, Mr0maks commented
> Надо-бы файлы локализации добавить

Добавлю сам

2022-12-10 05:38 UTC, merged

2022-12-10 05:55 UTC, CaptainSqrBeard commented
блин а чё такие айдишники всратые 💀