Arumoon server
Workbench-Team/space-station-14 pull request #70
Opened 2023-02-24 18:12 UTC by GuakeTheAcinid

## About the PR

**Media**

- [ ] Скриншот бутылок, коробки от них и сам факт спауна таковых в соответствующих шкафах и ящиках
![image](https://user-images.githubusercontent.com/126191483/221254607-1206faff-d71f-4677-9198-7c4b89e49b9d.png)
Скриншот наличия в протолате новых рецептов
![image](https://user-images.githubusercontent.com/126191483/221256001-ae232224-2b24-4696-8d98-7b884c5840ce.png)

**Changelog**
:cl:
- Добавлены: Прототипы большой и малой пластиковых бутылок, коробки из под пластиковых бутылок, спрайты для бутылок и коробки, рецепты бутылок в Протолат и медицинский ТехФаб, а также локализация для бутылок и коробки
- Изменено: Спаун в ящиках химического оборудования и в шкафах химиков: там теперь появляется 1 коробка из под бутылок; Изучение технологии химического оборудования теперь открывает рецепты бутылок в Протолате и медицинском ТехФабе

P.S.: первые парочку файлов кривовато вышли: спрайты коробок (оба файла) их meta.json, а также прототипы хим. оборудования в chemistry.yml. Они не изменили файлы, а заменили собой. По-идее это ничем не должно отличаться от того варианта, если бы их изменили по-нормальному.

2023-02-24 19:07 UTC, AruMoon requested changes
Судя по тестам, теперь цена продажи запасов для меда выше цены покупки
Нужно тогда повысить цену покупки MedicalChemistrySupplies, чтобы избежать фарма денег.
https://github.com/Workbench-Team/space-station-14/actions/runs/4265089459/jobs/7424006855#step:10:16

2023-02-24 21:39 UTC, CaptainSqrBeard commented
Мне кажется эффект разрушение от бросков это лишнее.
Также я не понимаю почему у файла с прототипами бутылок такой большой diff. Ещё у тебя походу английского .ftl нету для предметов

2023-02-25 05:04 UTC, GuakeTheAcinid commented
> Мне кажется эффект разрушение от бросков это лишнее. Также я не понимаю почему у файла с прототипами бутылок такой большой diff. Ещё у тебя походу английского .ftl нету для предметов (А ещё желательно с веб едита слезть)

1. Мне показалось, что пластиковые бутылки должны биться, если с ними обращаться неаккуратно (кидать/взрывать/резать), но поскольку пластик не такой хрупкий, как стекло, то выдерживает такое воздействие лучше. Хотелось бы сделать так, чтобы при больших или слишком малых температурах пластик разрушался, но пока не ясно как это сделать.

2. Файл с прототипами бутылок был скинут в качестве отдельного файла в папку назначения, и заменил собой существующий. То, на сколько diff окажется нечитабельным, получилось заметить только позже.

3. Я не в курсе что за "английский .ftl" должен быть и где именно его надо добавить. Будет приятно узнать что-то новое!

4. Будет здорово, если вы мне подскажете, как "слезть с веб едита"! Просто мне не очень ясно, как и куда.

2023-02-26 10:21 UTC, Mr0maks commented on Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
> +  cost: 1000
Предлагаю снизить до 850 - 900

2023-02-26 17:34 UTC, Mr0maks commented on Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
> -- type: entity
Почему diff таокй большой? Попробуй исправить.

2023-02-26 17:35 UTC, Mr0maks reviewed
В принципе LGTM, но картину портит большой diff у chemistry без всяких изменений. Надо исправить это.

2023-02-27 11:39 UTC, closed without merging