Reduced volume for dumplings sounds and added meow sound for toy-cat Shlepa
Workbench-Team/space-station-14 pull request #9
Opened 2022-12-11 16:14 UTC by PilgrimViis

Fixes #8

## About the PR 

**Changelog**
Из-за причин описанных в issue я решил сделать этот PR. У Ару была идея, сделать звуки пельменей тише. Я это реализовал. Плюс исправил баг, из-за которого кот шлёпа вместо мяуканья орал про пельмени.

2022-12-11 16:24 UTC, AruMoon requested changes
Просьба не использовать звуки с неизвестных источников. В игре уже есть звук мяукания, поэтому лучше использовать его
https://github.com/Workbench-Team/space-station-14/blob/arumoon-server/Resources/Audio/Animals/cat_meow.ogg

2022-12-11 16:26 UTC, AruMoon commented
Также звук пельменей стал слишком тихим

2022-12-11 17:46 UTC, Cooderer commented
Требую вернуть оригинальный огг пельменей, это каноничный звук шлепы в каске, для мяу можно сделать обычную плюшу шлепу - без каски

2022-12-12 00:00 UTC, PilgrimViis commented
Ладно, давайте сторгуемся на 30% от оригинальной громкости пельменей? Мяуканьте вставлю оригинальное.

2022-12-12 00:03 UTC, PilgrimViis commented
> Требую вернуть оригинальный огг пельменей, это каноничный звук шлепы в каске, для мяу можно сделать обычную плюшу шлепу - без каски

Я не понял, это было запланировано так что ли? А причем тут кот и пельмени? Я думал ты забыл поменять звук.

2022-12-14 14:54 UTC, PilgrimViis commented
@AruMoon Сделал

2022-12-14 16:10 UTC, merged